import React, { useState } from 'react';
import { openLighthouseReport, downloadLighthouseJson } from '../services/api';

// "View full Lighthouse report" + "Raw JSON" buttons for one saved audit.
// compact = small buttons for table rows.
const ReportButtons = ({ auditId, hasReport, compact = false }) => {
    const [busy, setBusy] = useState(false);
    const [error, setError] = useState(null);

    if (!auditId) return null;
    if (!hasReport) {
        return compact ? null : (
            <span className="report-buttons__none">No Lighthouse report saved for this audit (made before reports were added).</span>
        );
    }

    const run = async (fn) => {
        setBusy(true);
        setError(null);
        try { await fn(auditId); }
        catch (e) { setError(e.message || 'Could not load the report'); }
        finally { setBusy(false); }
    };

    return (
        <span className={`report-buttons ${compact ? 'report-buttons--compact' : ''}`}>
            <button type="button" className="report-buttons__view" disabled={busy}
                onClick={() => run(openLighthouseReport)}
                title="Open the original report generated by Lighthouse">
                {compact ? 'Report' : 'View full Lighthouse report'}
            </button>
            {!compact && (
                <button type="button" className="report-buttons__json" disabled={busy}
                    onClick={() => run(downloadLighthouseJson)}
                    title="Raw Lighthouse result — opens in the official Lighthouse Viewer">
                    Raw JSON
                </button>
            )}
            {error && <span className="report-buttons__error">{error}</span>}
        </span>
    );
};

export default ReportButtons;
